run:
  concurrency: 4
  timeout: 5m
  go: "1.21.1"
  # skip-dirs-use-default: true
  # modules-download-mode: readonly

output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  #
  # Multiple can be specified by separating them by comma, output can be provided
  # for each of them by separating format name and path by colon symbol.
  # Output path can be either `stdout`, `stderr` or path to the file to write to.
  # Example: "checkstyle:report.json,colored-line-number"
  #
  # Default: colored-line-number
  format: junit-xml

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - decorder
    # - depguard
    - dogsled
    - dupl
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - funlen
    - importas
    - nestif
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - predeclared
    - unparam
    - forbidigo

linters-settings:
  forbidigo:
    forbid:
      - '(exec.Command).("curl")*(# !!!DO NOT CALL CURL DIRECTLY!!!!\.)?'
  funlen:
    # Checks the number of lines in a function.
    # If lower than 0, disable the check.
    # Default: 60
    lines: 130
    # Checks the number of statements in a function.
    # If lower than 0, disable the check.
    # Default: 40
    statements: 80
