version: "3.3"
services:
  message-sender:
    image: golang:latest
    container_name: message-sender
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: bash
    working_dir: /go/src/message-sender
    volumes:
      - /home/borislav/GolangProjects/message-sender:/go/src/message-sender
    ports:
      - "8080:8080"
    # depends_on:
    # environment:
    #   VAULT_SERVERS: http://vault:8200
    #   VAULT_AUTH_TOKEN: root
    #   GOPRIVATE: gitlab.mansion.com/development/
    restart: on-failure:1000
#     networks:
#       - localhost
# networks:
#   default:
#   localhost:
